### ISSUE TITLE
maven编译报错

### ISSUE THREAD

**Issue by zhengshengjie666** [Auties00/WhatsappWeb4j#5] opened 2021-03-24 10:38 UTC
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project whatsappweb4j: Compilation failure: Compilation failure:
[ERROR] /opt/WhatsappWeb4j/src/main/java/it/auties/whatsapp4j/response/model/BinaryResponse.java: Error during the transformation of 'it.auties.whatsapp4j.response.model.BinaryResponse'; post-compiler 'lombok.bytecode.SneakyThrowsRemover' caused an exception: java.lang.UnsupportedOperationException: Records requires ASM8
我用的openjdk15

**Comment by Auties00** [comment] 2021-03-28 15:41
Hello, 
the issue is now fixed. Please check the new README.md for more information. If the issue persists, tell me

**Closed by Auties00** 2021-03-28 15:41 UTC
